### ISSUE TITLE
Flower seeds not plantable in modded soils/planters

### ISSUE THREAD

**Issue by Hahahavana** [ace10102/ArcaneFundamentals#1]
Specifically Farmer's Delight Rich Soil, and Supplementaries Planters. Presumably this also extends to other mod's soils.

**Comment by SpoilersMC** [comment]
Does this persist after adding said soils to the plantability tags for each flower crop?
~~I'll have to look at what the planters do, but I assume it's the same process but in the planter's tags~~
I took a look at supplementary, should be able to tag them plantable like any other block, but they seem to have an unresolved mod crop compat issue on their end which may apply here
https://github.com/MehVahdJukaar/Supplementaries/issues/88

**Comment by Hahahavana** [comment]
Serene seasons incompatibility doesn't actually affect planting/growing from what I've seen, plants that aren't compatible with it just use default behavior and grow normally. E.g. Occultism's Demon's Dream grows normally despite no compatibility, but just isn't affected by seasonal restrictions that are added. Demon's Dream is also plant-able in rich soil and the planters, so I don't think it'll be any issue.

I'd give you more technical answers, but the closest I have very little minecraft modding knowledge, sorry. Thanks a lot for looking into this though, I really appreciate it!.

**Comment by SpoilersMC** [comment]
No problem! ~~I could probably have a simplistic native support for some other modded farmlands by using the wheat plantable tag in my own tag for cerublossoms/aums~~ but imo if people want to grow wakeblooms and desert novas on farmlands then I've provided the tools to facilitate that, but won't make it default myself because I think it makes more sense for those two to grow on their natural spawning blocks
Edit: lol nevermind all generic vanilla crops have the same hardcoded check for farmland and nether wart isn't even classified as a crop so what I'm doing is already about as compatible as you can get
